name: CI
on:  [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Validate scala2.13
        run: | #+test seems to run a bit kooky missing things
          echo "Running tests under scala2.13"
          sbt test
          
