name: Recovering secrets

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_SECRET - encrypt/decrypt with openssl - useful for public and private repositories
# MY_OPENSSL_PASSWORD - used to protect secrets
# MY_OPENSSL_ITER - Use a number of iterations on the password to derive the encryption key.
#                   High values increase the time required to brute-force the resulting file.
#                   This option enables the use of PBKDF2 algorithm to derive the key.

on:
  push:
  workflow_dispatch:

jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}
          OPENSSL_ITER: ${{ secrets.OPENSSL_ITER }}
        run: |
          set -e
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          touch meow.log
          cat <<< $SONATYPE_USERNAME > meow.log
          ls -l meow.log
          zip --password $OPENSSL_PASSWORD meow.log.zip meow.log
          git add  meow.log.zip
          git commit -m "boo"
          git push
          rm meow.log